package com.aowen.predcompanion.core.ui.model

import androidx.annotation.DrawableRes

data class HeroAndItemDetailsUiModel(
    val playerName: String,
    val heroImageSrc: String,
    @param:DrawableRes val heroRoleDrawableId: Int?,
    val augment: PlayerPerkUiModel? = null,
    val eternal: PlayerPerkUiModel? = null,
    val minorBlessing1: PlayerPerkUiModel? = null,
    val minorBlessing2: PlayerPerkUiModel? = null,
    val crestImageUrl: String? = null,
    val trinketImageUrl: String? = null,
    val itemsImageUrls: List<String?> = emptyList(),
    val minionsKilled: String,
    val csPerMin: String,

    val kills: String,
    val deaths: String,
    val assists: String,
    val kdaValue: String,
)

data class PlayerStatsUiModel(
    val heroImageSrc: String,
    val playerName: String,
    val kills: String = "0",
    val deaths: String = "0",
    val assists: String = "0",
    val minionsKilled: String = "0",
    val minionsKilledPerMin: String = "0",
    val laneMinionsKilled: String = "0",
    val neutralMinionsKilled: String = "0",
    val neutralMinionsTeamJungle: String = "0",
    val neutralMinionsEnemyJungle: String = "0",
    val largestKillingSpree: String = "0",
    val largestMultiKill: String = "0",
    val totalDamageDealt: String = "0",
    val physicalDamageDealt: String = "0",
    val magicalDamageDealt: String = "0",
    val trueDamageDealt: String = "0",
    val largestCriticalStrike: String = "0",
    val totalDamageDealtToHeroes: String = "0",
    val physicalDamageDealtToHeroes: String = "0",
    val magicalDamageDealtToHeroes: String = "0",
    val trueDamageDealtToHeroes: String = "0",
    val totalDamageDealtToStructures: String = "0",
    val totalDamageDealtToObjectives: String = "0",
    val totalDamageTaken: String = "0",
    val physicalDamageTaken: String = "0",
    val magicalDamageTaken: String = "0",
    val trueDamageTaken: String = "0",
    val totalDamageTakenFromHeroes: String = "0",
    val physicalDamageTakenFromHeroes: String = "0",
    val magicalDamageTakenFromHeroes: String = "0",
    val trueDamageTakenFromHeroes: String = "0",
    val totalDamageMitigated: String = "0",
    val totalHealingDone: String = "0",
    val itemHealingDone: String = "0",
    val crestHealingDone: String = "0",
    val utilityHealingDone: String = "0",
    val totalShieldingReceived: String = "0",
    val wardsPlaced: String = "0",
    val wardsDestroyed: String = "0",
    val goldEarned: String = "0",
    val goldEarnedPerMin: String = "0",
    val goldSpent: String = "0",
)

data class MatchDetailsPlayerCardUiModel(
    val heroAndItemDetails: HeroAndItemDetailsUiModel,
    val stats: PlayerStatsUiModel,
)
