fragment MatchPlayerFragment on MatchPlayer {
    player {
        ...PlayerFragment
    }
    hero {
        ...HeroFragment
    }
    inventoryItemData {
        ...ItemDataFragment
    }
    team
    role
    kills
    deaths
    assists
    minionsKilled
    laneMinionsKilled
    neutralMinionsKilled
    neutralMinionsTeamJungle
    neutralMinionsEnemyJungle
    largestKillingSpree
    multiKill
    totalDamageDealt
    physicalDamageDealt
    magicalDamageDealt
    trueDamageDealt
    largestCriticalStrike
    heroDamage
    physicalDamageDealtToHeroes
    magicalDamageDealtToHeroes
    trueDamageDealtToHeroes
    totalDamageDealtToStructures
    totalDamageDealtToObjectives
    totalDamageTaken
    physicalDamageTaken
    magicalDamageTaken
    trueDamageTaken
    heroDamageTaken
    physicalDamageTakenFromHeroes
    magicalDamageTakenFromHeroes
    trueDamageTakenFromHeroes
    totalDamageMitigated
    totalHealingDone
    itemHealingDone
    crestHealingDone
    utilityHealingDone
    totalShieldingReceived
    wardsPlaced
    wardsDestroyed
    gold
    goldSpent
    rating {
        newPoints
        points
        rank {
            name
        }
    }
    perkData {
        slot
        icon
        displayName
        description

    }
}