fragment MatchResultsFragment on PaginatedPlayerMatches {
    results {
        role
        kills
        deaths
        assists
        team
        minionsKilled
        player {
            id
        }
        inventoryItemData {
            ...ItemDataFragment
        }
        perkData {
            slot
            icon
        }
        heroData {
            hero {
                id
            }
            displayName
            icon
            id
        }
        rating {
            newPoints
            points
        }
        match {
            id
            winningTeam
            gameMode
            endTime
            startTime
        }
    }
}