fragment PlayerFragment on Player {
    id
    name
    favRole
    ratings {
        ...PlayerRatingFragment
    }
    favHero {
        ...HeroFragment
    }
    generalStatistic {
        result {
            matchesPlayed
            matchesWon
        }
    }
    heroStatistics {
        results {
            hero {
                ...HeroFragment
            }
            matchesPlayed
            matchesWon
            totalKills
            totalDeaths
            totalAssists
        }
    }
}