name: Distribute to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build Debug APK
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: ./gradlew assembleRelease
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Setup service account
        run: echo ${{ secrets.CREDENTIAL_FILE_CONTENT }} > $HOME/serviceAccountKey.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/serviceAccountKey.json

      - name: Deploy to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/serviceAccountKey.json
        run: |
          firebase appdistribution:distribute ${{ secrets.APP_FILE_PATH }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups close-friends \
          --release-notes-file RELEASENOTES.md
