name: Send to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Debug APK
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: ./gradlew assembleRelease

      - name: Decode Firebase service account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > ./serviceAccountKey.json
        shell: bash

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase apps:list --project monolith-aowen
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json

      - name: Distribute to Firebase
        run: |
          firebase appdistribution:distribute ${{ secrets.APP_FILE_PATH }} --app ${{ secrets.FIREBASE_APP_ID }} --groups close-friends --release-notes-file RELEASENOTES.md
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json
