name: Distribute to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.6.0
        with:
          appId: 1:325875259106:android:a41924af78a6fed3de70bb
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: close-friends # or whatever tester group you have defined
          file: app/build/outputs/apk/debug/app-debug.apk
