name: Send to Firebase App Distribution

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  distribute:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set version variable
        run: |
          VERSION_NAME=$(echo "${{ github.ref_name }}" | egrep -o '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version_name=$VERSION_NAME" >> "$GITHUB_ENV"

      - name: Build & Assemble Release APK
        env:
          VERSION_CODE: ${{ github.run_number }}
          VERSION_NAME: ${{ env.version_name }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: ./gradlew assembleFirebaseDistribution

      - name: Decode Firebase service account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > ./serviceAccountKey.json
        shell: bash

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase apps:list --project monolith-aowen
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json

      - name: Distribute to Firebase
        run: |
          firebase appdistribution:distribute ${{ secrets.APP_FILE_PATH }} --app ${{ secrets.FIREBASE_APP_ID }} --groups close-friends --release-notes-file RELEASENOTES.md
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            app/build/outputs/apk/firebaseDistribution/app-firebaseDistribution.apk
