name: Distribute to Firebase App Distribution
on:
  push:
    branches:
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Access SUPABASE_URL
        env:
          SUPABASE_URL: $
          SUPABASE_KEY: $
        run: |
          echo SUPABASE_URL=\"$SUPABASE_URL\" > ./local.properties \
          echo SUPABASE_KEY=\"$SUPABASE_KEY\" >> ./local.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.6.0
        with:
          appId: 1:325875259106:android:a41924af78a6fed3de70bb
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: close-friends # or whatever tester group you have defined
          file: app/build/outputs/apk/debug/app-debug.apk